In [2]:
import os
import logging
import random
import gc
import time
import cv2
import math
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
import librosa

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.optim import lr_scheduler
from torch.utils.data import Dataset, DataLoader

import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.auto import tqdm

import timm

warnings.filterwarnings("ignore")
logging.basicConfig(level=logging.ERROR)

In [27]:
import numpy as np

# Replace 'path/to/file.npy' with your actual filename
arr = np.load('/kaggle/input/mel-spec-npy-dict/mel_specs (1).npy', allow_pickle=True).item()

# inspect
print(type(arr))  

<class 'dict'>


In [28]:
import itertools
for key, value in itertools.islice(arr.items(), 5):
    print(f"Key: {key}")
    print(f"Value:\n{value}\n")

Key: 1139490/CSA36385.ogg
Value:
[[0.01789158 0.         0.         ... 0.5486588  0.62437123 0.6126248 ]
 [0.01626605 0.         0.         ... 0.55647945 0.62296313 0.62886786]
 [0.013015   0.         0.         ... 0.5721207  0.620147   0.6613538 ]
 ...
 [0.09885019 0.05090576 0.05342069 ... 0.37939176 0.3772261  0.49574164]
 [0.09692583 0.01696859 0.0178069  ... 0.12646392 0.12574203 0.37073165]
 [0.09596366 0.         0.         ... 0.         0.         0.30822667]]

Key: 1139490/CSA36389.ogg
Value:
[[0.         0.         0.         ... 0.02069894 0.00536066 0.10744955]
 [0.         0.         0.         ... 0.07629509 0.04058953 0.12448078]
 [0.         0.         0.         ... 0.18748736 0.11104726 0.15854324]
 ...
 [0.         0.         0.         ... 0.5650746  0.59219754 0.70578283]
 [0.         0.         0.         ... 0.1883582  0.19739917 0.5114504 ]
 [0.         0.         0.         ... 0.         0.         0.41428423]]

Key: 1192948/CSA36358.ogg
Value:
[[0.3003291

In [5]:
class CFG:
    
    seed = 42
    debug = False  
    apex = False
    print_freq = 100
    num_workers = 2
    
    OUTPUT_DIR = '/kaggle/working/'

    train_datadir = '/kaggle/input/birdclef-2025/train_audio'
    train_csv = '/kaggle/input/birdclef-2025/train.csv'
    test_soundscapes = '/kaggle/input/birdclef-2025/test_soundscapes'
    submission_csv = '/kaggle/input/birdclef-2025/sample_submission.csv'
    taxonomy_csv = '/kaggle/input/birdclef-2025/taxonomy.csv'

    spectrogram_npy = '/kaggle/input/mel-spec-npy-dict/mel_specs (1).npy'

    model_name = 'efficientnet_b0'
    
    pretrained = True
    in_channels = 1

    LOAD_DATA = True  
    sample_rate = 32000
    target_duration = 5.0
    target_shape = (256, 256)
    
    n_fft = 1024
    hop_length = 512
    n_mels = 128
    f_min = 20
    f_max = 16000
    
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    epochs = 10  
    batch_size = 32  
    criterion = 'BCEWithLogitsLoss'

    n_fold = 3
    selected_folds = [0, 1, 2]   

    optimizer = 'AdamW'
    lr = 5e-4 
    weight_decay = 1e-5
  
    scheduler = 'CosineAnnealingLR'
    min_lr = 1e-6
    T_max = epochs

    aug_prob = 0.5  
    mixup_alpha = 0.5  
    
    def update_debug_settings(self):
        if self.debug:
            self.epochs = 2
            self.selected_folds = [0]

cfg = CFG()

In [6]:
train_df = pd.read_csv(cfg.train_csv)
print(train_df.head())
print("\nExample filename from train_df:", train_df['filename'].iloc[0])

  primary_label secondary_labels  type              filename collection  \
0       1139490             ['']  ['']  1139490/CSA36385.ogg        CSA   
1       1139490             ['']  ['']  1139490/CSA36389.ogg        CSA   
2       1192948             ['']  ['']  1192948/CSA36358.ogg        CSA   
3       1192948             ['']  ['']  1192948/CSA36366.ogg        CSA   
4       1192948             ['']  ['']  1192948/CSA36373.ogg        CSA   

   rating                                                url  latitude  \
0     0.0  http://colecciones.humboldt.org.co/rec/sonidos...    7.3206   
1     0.0  http://colecciones.humboldt.org.co/rec/sonidos...    7.3206   
2     0.0  http://colecciones.humboldt.org.co/rec/sonidos...    7.3791   
3     0.0  http://colecciones.humboldt.org.co/rec/sonidos...    7.2800   
4     0.0  http://colecciones.humboldt.org.co/rec/sonidos...    7.3791   

   longitude        scientific_name            common_name             author  \
0   -73.7128   Ragoniel

In [7]:
def set_seed(seed=42):
    """
    Set seed for reproducibility
    """
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(cfg.seed)

In [8]:
class BirdCLEFDatasetFromNPY(Dataset):
    def __init__(self, df, cfg, spectrograms=None, mode="train"):
        self.df = df
        self.cfg = cfg
        self.mode = mode

        self.spectrograms = spectrograms
        
        taxonomy_df = pd.read_csv(self.cfg.taxonomy_csv)
        self.species_ids = taxonomy_df['primary_label'].tolist()
        self.num_classes = len(self.species_ids)
        self.label_to_idx = {label: idx for idx, label in enumerate(self.species_ids)}

        if 'filepath' not in self.df.columns:
            self.df['filepath'] = self.cfg.train_datadir + '/' + self.df.filename
        
        if 'samplename' not in self.df.columns:
            self.df['samplename'] = self.df.filename.map(lambda x: x.split('/')[0] + '-' + x.split('/')[-1].split('.')[0])

        filenames_set = set(self.df['filename']) # Use 'filename'
        if self.spectrograms:
            found_samples = sum(1 for name in filenames_set if name in self.spectrograms) # Compare filename to keys
            print(f"Found {found_samples} matching spectrograms for {mode} dataset out of {len(self.df)} samples")
        
        if cfg.debug:
            self.df = self.df.sample(min(1000, len(self.df)), random_state=cfg.seed).reset_index(drop=True)
    
    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
       
        filename = row['filename'] 
        spec = None

        # --- CHANGE: Use 'filename' as the key ---
        if self.spectrograms and filename in self.spectrograms:
            spec = self.spectrograms[filename]
        elif not self.cfg.LOAD_DATA:
            # This part will likely not run, but keep it as a fallback
            spec = process_audio_file(row['filepath'], self.cfg)

        if spec is None:
            spec = np.zeros(self.cfg.TARGET_SHAPE, dtype=np.float32)
            if self.mode == "train": 
                print(f"Warning: Spectrogram for {filename} not found and could not be generated")

        spec = torch.tensor(spec, dtype=torch.float32).unsqueeze(0)  # Add channel dimension

        if self.mode == "train" and random.random() < self.cfg.aug_prob:
            spec = self.apply_spec_augmentations(spec)
        
        target = self.encode_label(row['primary_label'])
        
        if 'secondary_labels' in row and row['secondary_labels'] not in [[''], None, np.nan]:
            if isinstance(row['secondary_labels'], str):
                secondary_labels = eval(row['secondary_labels'])
            else:
                secondary_labels = row['secondary_labels']
            
            for label in secondary_labels:
                if label in self.label_to_idx:
                    target[self.label_to_idx[label]] = 1.0
        
        return {
            'melspec': spec, 
            'target': torch.tensor(target, dtype=torch.float32),
            'filename': row['filename']
        }

    def apply_spec_augmentations(self, spec):
        # This function remains the same
        if random.random() < 0.5:
            num_masks = random.randint(1, 3)
            for _ in range(num_masks):
                width = random.randint(5, 20)
                start = random.randint(0, spec.shape[2] - width)
                spec[0, :, start:start+width] = 0
        
        if random.random() < 0.5:
            num_masks = random.randint(1, 3)
            for _ in range(num_masks):
                height = random.randint(5, 20)
                start = random.randint(0, spec.shape[1] - height)
                spec[0, start:start+height, :] = 0
        
        if random.random() < 0.5:
            gain = random.uniform(0.8, 1.2)
            bias = random.uniform(-0.1, 0.1)
            spec = spec * gain + bias
            spec = torch.clamp(spec, 0, 1) 
            
        return spec
    
    def encode_label(self, label):
        # This function remains the same
        target = np.zeros(self.num_classes)
        if label in self.label_to_idx:
            target[self.label_to_idx[label]] = 1.0
        return target
    
    

In [9]:
def collate_fn(batch):
    """Custom collate function to handle different sized spectrograms"""
    batch = [item for item in batch if item is not None]
    if len(batch) == 0:
        return {}
        
    result = {key: [] for key in batch[0].keys()}
    
    for item in batch:
        for key, value in item.items():
            result[key].append(value)
    
    for key in result:
        if key == 'target' and isinstance(result[key][0], torch.Tensor):
            result[key] = torch.stack(result[key])
        elif key == 'melspec' and isinstance(result[key][0], torch.Tensor):
            shapes = [t.shape for t in result[key]]
            if len(set(str(s) for s in shapes)) == 1:
                result[key] = torch.stack(result[key])
    
    return result

In [10]:
class BirdCLEFModel(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        self.cfg = cfg
        
        taxonomy_df = pd.read_csv(cfg.taxonomy_csv)
        cfg.num_classes = len(taxonomy_df)
        
        self.backbone = timm.create_model(
            cfg.model_name,
            pretrained=cfg.pretrained,
            in_chans=cfg.in_channels,
            drop_rate=0.2,
            drop_path_rate=0.2
        )

        if 'efficientnet' in cfg.model_name:
                backbone_out = self.backbone.classifier.in_features
                self.backbone.classifier = nn.Identity()
        elif 'resnet' in cfg.model_name:
            backbone_out = self.backbone.fc.in_features
            self.backbone.fc = nn.Identity()
        else:
            backbone_out = self.backbone.get_classifier().in_features
            self.backbone.reset_classifier(0, '')
        
        self.pooling = nn.AdaptiveAvgPool2d(1)
            
        self.feat_dim = backbone_out
        
        self.classifier = nn.Linear(backbone_out, cfg.num_classes)
        
        self.mixup_enabled = hasattr(cfg, 'mixup_alpha') and cfg.mixup_alpha > 0
        if self.mixup_enabled:
            self.mixup_alpha = cfg.mixup_alpha

    def forward(self, x, targets=None):
        if self.training and self.mixup_enabled and targets is not None:
            mixed_x, targets_a, targets_b, lam = self.mixup_data(x, targets)
            x = mixed_x
        else:
            targets_a, targets_b, lam = None, None, None
        
        features = self.backbone(x)
        
        if isinstance(features, dict):
            features = features['features']
            
        if len(features.shape) == 4:
            features = self.pooling(features)
            features = features.view(features.size(0), -1)
        
        logits = self.classifier(features)
        
        if self.training and self.mixup_enabled and targets is not None:
            loss = self.mixup_criterion(F.binary_cross_entropy_with_logits, 
                                       logits, targets_a, targets_b, lam)
            return logits, loss
            
        return logits

    def mixup_data(self, x, targets):
        """Applies mixup to the data batch"""
        batch_size = x.size(0)

        lam = np.random.beta(self.mixup_alpha, self.mixup_alpha)

        indices = torch.randperm(batch_size).to(x.device)

        mixed_x = lam * x + (1 - lam) * x[indices]
        
        return mixed_x, targets, targets[indices], lam
    
    def mixup_criterion(self, criterion, pred, y_a, y_b, lam):
        """Applies mixup to the loss function"""
        return lam * criterion(pred, y_a) + (1 - lam) * criterion(pred, y_b)

In [11]:
def get_optimizer(model, cfg):
  
    if cfg.optimizer == 'Adam':
        optimizer = optim.Adam(
            model.parameters(),
            lr=cfg.lr,
            weight_decay=cfg.weight_decay
        )
    elif cfg.optimizer == 'AdamW':
        optimizer = optim.AdamW(
            model.parameters(),
            lr=cfg.lr,
            weight_decay=cfg.weight_decay
        )
    elif cfg.optimizer == 'SGD':
        optimizer = optim.SGD(
            model.parameters(),
            lr=cfg.lr,
            momentum=0.9,
            weight_decay=cfg.weight_decay
        )
    else:
        raise NotImplementedError(f"Optimizer {cfg.optimizer} not implemented")
        
    return optimizer

def get_scheduler(optimizer, cfg):
   
    if cfg.scheduler == 'CosineAnnealingLR':
        scheduler = lr_scheduler.CosineAnnealingLR(
            optimizer,
            T_max=cfg.T_max,
            eta_min=cfg.min_lr
        )
    elif cfg.scheduler == 'ReduceLROnPlateau':
        scheduler = lr_scheduler.ReduceLROnPlateau(
            optimizer,
            mode='min',
            factor=0.5,
            patience=2,
            min_lr=cfg.min_lr,
            verbose=True
        )
    elif cfg.scheduler == 'StepLR':
        scheduler = lr_scheduler.StepLR(
            optimizer,
            step_size=cfg.epochs // 3,
            gamma=0.5
        )
    elif cfg.scheduler == 'OneCycleLR':
        scheduler = None  
    else:
        scheduler = None
        
    return scheduler

def get_criterion(cfg):
 
    if cfg.criterion == 'BCEWithLogitsLoss':
        criterion = nn.BCEWithLogitsLoss()
    else:
        raise NotImplementedError(f"Criterion {cfg.criterion} not implemented")
        
    return criterion

In [12]:
def train_one_epoch(model, loader, optimizer, criterion, device, scheduler=None):
    
    model.train()
    losses = []
    all_targets = []
    all_outputs = []
    
    pbar = tqdm(enumerate(loader), total=len(loader), desc="Training")
    
    for step, batch in pbar:
    
        if isinstance(batch['melspec'], list):
            batch_outputs = []
            batch_losses = []
            
            for i in range(len(batch['melspec'])):
                inputs = batch['melspec'][i].unsqueeze(0).to(device)
                target = batch['target'][i].unsqueeze(0).to(device)
                
                optimizer.zero_grad()
                output = model(inputs)
                loss = criterion(output, target)
                loss.backward()

                batch_outputs.append(output.detach().cpu())
                batch_losses.append(loss.item())

            optimizer.step()
            outputs = torch.cat(batch_outputs, dim=0).numpy()
            loss = np.mean(batch_losses)
            targets = batch['target'].numpy()
        else:
            inputs = batch['melspec'].to(device)
            targets = batch['target'].to(device)
            
            optimizer.zero_grad()
            outputs = model(inputs)
            
            if isinstance(outputs, tuple):
                outputs, loss = outputs  
            else:
                loss = criterion(outputs, targets)
                
            loss.backward()
            optimizer.step()
            
            outputs = outputs.detach().cpu().numpy()
            targets = targets.detach().cpu().numpy()

        if scheduler is not None and isinstance(scheduler, lr_scheduler.OneCycleLR):
            scheduler.step()
            
        all_outputs.append(outputs)
        all_targets.append(targets)
        losses.append(loss if isinstance(loss, float) else loss.item())
        
        pbar.set_postfix({
            'train_loss': np.mean(losses[-10:]) if losses else 0,
            'lr': optimizer.param_groups[0]['lr']
        })
    
    all_outputs = np.concatenate(all_outputs)
    all_targets = np.concatenate(all_targets)
    auc = calculate_auc(all_targets, all_outputs)
    avg_loss = np.mean(losses)
    
    return avg_loss, auc
            
def validate(model, loader, criterion, device):
   
    model.eval()
    losses = []
    all_targets = []
    all_outputs = []
    
    with torch.no_grad():
        for batch in tqdm(loader, desc="Validation"):
            if isinstance(batch['melspec'], list):
                batch_outputs = []
                batch_losses = []
                
                for i in range(len(batch['melspec'])):
                    inputs = batch['melspec'][i].unsqueeze(0).to(device)
                    target = batch['target'][i].unsqueeze(0).to(device)
                    
                    output = model(inputs)
                    loss = criterion(output, target)
                    
                    batch_outputs.append(output.detach().cpu())
                    batch_losses.append(loss.item())

                outputs = torch.cat(batch_outputs, dim=0).numpy()
                loss = np.mean(batch_losses)
                targets = batch['target'].numpy()
            else:
                inputs = batch['melspec'].to(device)
                targets = batch['target'].to(device)
                
                outputs = model(inputs)
                loss = criterion(outputs, targets)
                
                outputs = outputs.detach().cpu().numpy()
                targets = targets.detach().cpu().numpy()
            
            all_outputs.append(outputs)
            all_targets.append(targets)
            losses.append(loss if isinstance(loss, float) else loss.item())

    all_outputs = np.concatenate(all_outputs)
    all_targets = np.concatenate(all_targets)
    
    auc = calculate_auc(all_targets, all_outputs)
    avg_loss = np.mean(losses)
    
    return avg_loss, auc

def calculate_auc(targets, outputs):
  
    num_classes = targets.shape[1]
    aucs = []
    
    probs = 1 / (1 + np.exp(-outputs))
    
    for i in range(num_classes):
        
        if np.sum(targets[:, i]) > 0:
            class_auc = roc_auc_score(targets[:, i], probs[:, i])
            aucs.append(class_auc)
    
    return np.mean(aucs) if aucs else 0.0

In [13]:
def run_training(df, cfg):
    """Training function that can either use pre-computed spectrograms or generate them on-the-fly"""

    taxonomy_df = pd.read_csv(cfg.taxonomy_csv)
    species_ids = taxonomy_df['primary_label'].tolist()
    cfg.num_classes = len(species_ids)
    
    if cfg.debug:
        cfg.update_debug_settings()

    spectrograms = None
    if cfg.LOAD_DATA:
        print("Loading pre-computed mel spectrograms from NPY file...")
        try:
            spectrograms = np.load(cfg.spectrogram_npy, allow_pickle=True).item()
            print(f"Loaded {len(spectrograms)} pre-computed mel spectrograms")
        except Exception as e:
            print(f"Error loading pre-computed spectrograms: {e}")
            print("Will generate spectrograms on-the-fly instead.")
            cfg.LOAD_DATA = False
    skf = StratifiedKFold(n_splits=cfg.n_fold, shuffle=True, random_state=cfg.seed)

    best_scores = []
    
    for fold, (train_idx, val_idx) in enumerate(skf.split(df, df['primary_label'])):
        if fold not in cfg.selected_folds:
            continue
            
        print(f'\n{"="*30} Fold {fold} {"="*30}')
        
        train_df = df.iloc[train_idx].reset_index(drop=True)
        val_df = df.iloc[val_idx].reset_index(drop=True)
        
        print(f'Training set: {len(train_df)} samples')
        print(f'Validation set: {len(val_df)} samples')
        
        train_dataset = BirdCLEFDatasetFromNPY(train_df, cfg, spectrograms=spectrograms, mode='train')
        val_dataset = BirdCLEFDatasetFromNPY(val_df, cfg, spectrograms=spectrograms, mode='valid')

        train_loader = DataLoader(
            train_dataset, 
            batch_size=cfg.batch_size, 
            shuffle=True, 
            num_workers=cfg.num_workers,
            pin_memory=True,
            collate_fn=collate_fn,
            drop_last=True
        )
        
        val_loader = DataLoader(
            val_dataset, 
            batch_size=cfg.batch_size, 
            shuffle=False, 
            num_workers=cfg.num_workers,
            pin_memory=True,
            collate_fn=collate_fn
        )

        model = BirdCLEFModel(cfg).to(cfg.device)
        optimizer = get_optimizer(model, cfg)
        criterion = get_criterion(cfg)
        
        if cfg.scheduler == 'OneCycleLR':
            scheduler = lr_scheduler.OneCycleLR(
                optimizer,
                max_lr=cfg.lr,
                steps_per_epoch=len(train_loader),
                epochs=cfg.epochs,
                pct_start=0.1
            )
        else:
            scheduler = get_scheduler(optimizer, cfg)
        
        best_auc = 0
        best_epoch = 0

        for epoch in range(cfg.epochs):
            print(f"\nEpoch {epoch+1}/{cfg.epochs}")
            
            train_loss, train_auc = train_one_epoch(
                model, 
                train_loader, 
                optimizer, 
                criterion, 
                cfg.device,
                scheduler if isinstance(scheduler, lr_scheduler.OneCycleLR) else None
            )
            
            val_loss, val_auc = validate(model, val_loader, criterion, cfg.device)

            if scheduler is not None and not isinstance(scheduler, lr_scheduler.OneCycleLR):
                if isinstance(scheduler, lr_scheduler.ReduceLROnPlateau):
                    scheduler.step(val_loss)
                else:
                    scheduler.step()

            print(f"Train Loss: {train_loss:.4f}, Train AUC: {train_auc:.4f}")
            print(f"Val Loss: {val_loss:.4f}, Val AUC: {val_auc:.4f}")

            if val_auc > best_auc:
                best_auc = val_auc
                best_epoch = epoch + 1
                print(f"New best AUC: {best_auc:.4f} at epoch {best_epoch}")

                torch.save({
                    'model_state_dict': model.state_dict(),
                    'optimizer_state_dict': optimizer.state_dict(),
                    'scheduler_state_dict': scheduler.state_dict() if scheduler else None,
                    'epoch': epoch,
                    'val_auc': val_auc,
                    'train_auc': train_auc,
                    'cfg': cfg
                }, f"model_fold{fold}.pth")

        best_scores.append(best_auc)
        print(f"\nBest AUC for fold {fold}: {best_auc:.4f} at epoch {best_epoch}")
        
        # Clear memory
        del model, optimizer, scheduler, train_loader, val_loader
        torch.cuda.empty_cache()
        gc.collect()

    print("\n" + "="*60)
    print("Cross-Validation Results:")
    for fold, score in enumerate(best_scores):
        print(f"Fold {cfg.selected_folds[fold]}: {score:.4f}")
    print(f"Mean AUC: {np.mean(best_scores):.4f}")
    print("="*60)

In [ ]:
if __name__ == "__main__":
    import time
    
    print("\nLoading training data...")
    train_df = pd.read_csv(cfg.train_csv)
    taxonomy_df = pd.read_csv(cfg.taxonomy_csv)

    print("\nStarting training...")
    print(f"LOAD_DATA is set to {cfg.LOAD_DATA}")
    if cfg.LOAD_DATA:
        print("Using pre-computed mel spectrograms from NPY file")
    else:
        print("Will generate spectrograms on-the-fly during training")
    
    run_training(train_df, cfg)
    
    print("\nTraining complete!")


Loading training data...

Starting training...
LOAD_DATA is set to True
Using pre-computed mel spectrograms from NPY file
Loading pre-computed mel spectrograms from NPY file...
Loaded 28564 pre-computed mel spectrograms

============================== Fold 0 ==============================
Training set: 19042 samples
Validation set: 9522 samples
Found 19042 matching spectrograms for train dataset out of 19042 samples
Found 9522 matching spectrograms for valid dataset out of 9522 samples


model.safetensors:   0%|          | 0.00/21.4M [00:00<?, ?B/s]


Epoch 1/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0390, Train AUC: 0.5566
Val Loss: 0.0267, Val AUC: 0.7895
New best AUC: 0.7895 at epoch 1

Epoch 2/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7960af65d580>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py", line 1618, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py", line 1601, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process


Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0236, Train AUC: 0.8132
Val Loss: 0.0193, Val AUC: 0.9122
New best AUC: 0.9122 at epoch 2

Epoch 3/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0184, Train AUC: 0.9152
Val Loss: 0.0161, Val AUC: 0.9395
New best AUC: 0.9395 at epoch 3

Epoch 4/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0153, Train AUC: 0.9481
Val Loss: 0.0147, Val AUC: 0.9472
New best AUC: 0.9472 at epoch 4

Epoch 5/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0129, Train AUC: 0.9661
Val Loss: 0.0140, Val AUC: 0.9519
New best AUC: 0.9519 at epoch 5

Epoch 6/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0107, Train AUC: 0.9816
Val Loss: 0.0132, Val AUC: 0.9574
New best AUC: 0.9574 at epoch 6

Epoch 7/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0089, Train AUC: 0.9897
Val Loss: 0.0132, Val AUC: 0.9575
New best AUC: 0.9575 at epoch 7

Epoch 8/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0074, Train AUC: 0.9936
Val Loss: 0.0133, Val AUC: 0.9575

Epoch 9/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0064, Train AUC: 0.9956
Val Loss: 0.0132, Val AUC: 0.9575

Epoch 10/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0059, Train AUC: 0.9966
Val Loss: 0.0132, Val AUC: 0.9582
New best AUC: 0.9582 at epoch 10

Best AUC for fold 0: 0.9582 at epoch 10

============================== Fold 1 ==============================
Training set: 19043 samples
Validation set: 9521 samples
Found 19043 matching spectrograms for train dataset out of 19043 samples
Found 9521 matching spectrograms for valid dataset out of 9521 samples

Epoch 1/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0374, Train AUC: 0.5905
Val Loss: 0.0248, Val AUC: 0.8289
New best AUC: 0.8289 at epoch 1

Epoch 2/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0225, Train AUC: 0.8391
Val Loss: 0.0187, Val AUC: 0.9117
New best AUC: 0.9117 at epoch 2

Epoch 3/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0151, Train AUC: 0.9442
Val Loss: 0.0148, Val AUC: 0.9505
New best AUC: 0.9505 at epoch 4

Epoch 5/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0129, Train AUC: 0.9667
Val Loss: 0.0142, Val AUC: 0.9556
New best AUC: 0.9556 at epoch 5

Epoch 6/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0110, Train AUC: 0.9788
Val Loss: 0.0136, Val AUC: 0.9583
New best AUC: 0.9583 at epoch 6

Epoch 7/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0091, Train AUC: 0.9887
Val Loss: 0.0134, Val AUC: 0.9615
New best AUC: 0.9615 at epoch 7

Epoch 8/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0076, Train AUC: 0.9930
Val Loss: 0.0133, Val AUC: 0.9610

Epoch 9/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0066, Train AUC: 0.9953
Val Loss: 0.0134, Val AUC: 0.9609

Epoch 10/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0061, Train AUC: 0.9962
Val Loss: 0.0134, Val AUC: 0.9604

Best AUC for fold 1: 0.9615 at epoch 7

============================== Fold 2 ==============================
Training set: 19043 samples
Validation set: 9521 samples
Found 19043 matching spectrograms for train dataset out of 19043 samples
Found 9521 matching spectrograms for valid dataset out of 9521 samples

Epoch 1/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0385, Train AUC: 0.5368
Val Loss: 0.0273, Val AUC: 0.7849
New best AUC: 0.7849 at epoch 1

Epoch 2/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0241, Train AUC: 0.8123
Val Loss: 0.0202, Val AUC: 0.8902
New best AUC: 0.8902 at epoch 2

Epoch 3/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0192, Train AUC: 0.8968
Val Loss: 0.0171, Val AUC: 0.9310
New best AUC: 0.9310 at epoch 3

Epoch 4/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0161, Train AUC: 0.9383
Val Loss: 0.0154, Val AUC: 0.9423
New best AUC: 0.9423 at epoch 4

Epoch 5/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0137, Train AUC: 0.9610
Val Loss: 0.0146, Val AUC: 0.9482
New best AUC: 0.9482 at epoch 5

Epoch 6/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0116, Train AUC: 0.9763
Val Loss: 0.0138, Val AUC: 0.9573
New best AUC: 0.9573 at epoch 6

Epoch 7/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0099, Train AUC: 0.9862
Val Loss: 0.0134, Val AUC: 0.9584
New best AUC: 0.9584 at epoch 7

Epoch 8/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0083, Train AUC: 0.9912
Val Loss: 0.0134, Val AUC: 0.9570

Epoch 9/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]

Validation:   0%|          | 0/298 [00:00<?, ?it/s]

Train Loss: 0.0073, Train AUC: 0.9940
Val Loss: 0.0134, Val AUC: 0.9584

Epoch 10/10


Training:   0%|          | 0/595 [00:00<?, ?it/s]